import streamlit as st

import datetime
import requests
import sys

BASE_URL = "http://127.0.0.1:8000"

st.set_page_config(page_title="Travel Planner", page_icon=":airplane:", 
layout="centered",initial_sidebar_state="expanded")
st.title("Travel Planner")
if "messages" not in st.session_state:
    st.session_state.messages = []



st.header("Plan your trip to any place worldwide with real-time data from internet.")


with st.form(key="trip_form"):
    user_input = st.text_input("Enter your destination")
    submitted = st.form_submit_button("Submit")

if submitted and user_input.strip():
    
    try:
        #show user message
        #show the thinking spinner while the backend is processing the request
        with st.spinner("engine is planning you trip..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code  == 200:
            answer = response.json().get("answer", "No answer returned")
            markdown_answer = f"""## Travel Plan 
            #Generated at: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            #created by: AI Travel Agent

             {answer}
             


             #This travel plan is generated by AI.Please verify the information before you travel.
             """

            st.markdown(markdown_answer)

        else:
            st.error(f"Error: {response.status_code} - {response.text}")

    except Exception as e:
        st.error(f"Error: {e}")
        st.error(f"Error: {e}")
